# #####################################################################
#                 MapProxy example configuration
# #####################################################################
#
# This is _not_ a runnable configuration, but it contains most
# available options in meaningful combinations.
#
# Use this file in addition to the documentation to see where and how
# things can be configured.


services:
  demo:
  wms:
    # only offer WMS 1.1.1
    versions: ['1.1.1', '1.3.0']
    # supported SRS for this WMS
    srs: ['EPSG:4326', 'EPSG:3857']
    # force the layer extents (BBOX) to be displayed in this SRS
    bbox_srs: ['EPSG:4326']
    # limit the supported image formats.
    image_formats: ['image/jpeg', 'image/png', 'image/gif', 'image/GeoTIFF', 'image/tiff']
    # return an OGC service exception when one or more sources return errors
    # or no response at all (e.g. timeout)
    on_source_errors: raise

    # some WMS clients do not send all required parameters in feature info
    # requests, MapProxy ignores these errors unless you set strict to true.
    strict: true

    # list of feature info types the server should offer
    featureinfo_types: ['text', 'html', 'xml']

    md:
      # metadata used in capabilities documents
      title: Mapproxy demo map
      abstract: The map showing how QGIS Server interacts with Mapproxy.
      online_resource: http://kartoza.com/
      contact:
        person: Kartoza
        position: GIS Manager
        organization:
        address:
        city:
        postcode:
        country: south Africa
        phone:
        email:
      access_constraints:
        Insert license and copyright information for this service.
      fees: 'None'
  tms:
    use_grid_names: true
  wmts:
    restful: true
    restful_template: '/{Layer}/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.{Format}'
    kvp: true
  kml:
    use_grid_names: true

layers:

  #sets up which layers you want to make available using the services above. You can add many, but let's stick to osm data here.
  - name: osm
    title: Open Streetmap Tiles
    sources: [osm_cache] #this layer should use the osm_cache (defined below) as it's source.

  - name: Hillshade
    title: Hillshade
    sources: [hillshade_cache]


  - name: SRTM
    title: SRTM 30m
    sources: [srtm_cache]

  - name: airports
    title: Airports
    sources: [airports_cache]



caches:

  #setup the cache for the open streetmap tiles. This cache is used by the layer above.
  osm_cache:
    sources: [osm_tiles] #here you set what source data (defined below) you want to cache
    format: image/png

  airports_cache:
    sources: [airports_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2
    cache:
      type: mbtiles
      filename: ./cache_data/airports.mbtiles



  srtm_cache:
    sources: [srtm_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2
    cache:
      type: file
      directory: ./cache_data/srtm_cache
    format: custom_format

  hillshade_cache:
    sources: [hillshade_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2
    cache:
      type: mbtiles
      filename: ./cache_data/hillshade.mbtiles

sources:
   osm_tiles:
     #the osm_tiles source refers to the openstreetmap.org tiles. These will be downloaded upon request (if not already cached) and served by MapProxy
     type: tile
     url: http://tile.openstreetmap.org/%(tms_path)s.%(format)s
     grid: osm_grid2 #the grid to use for the osm tiles. This is really important. It is specified below.

  hillshade_wms:
    coverage:

      bbox: [20, -9.99999999998001, 59.999999999984, 40]
      bbox_srs: EPSG:4326
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: Hillshade
      transparent: true
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']


  srtm_wms:
    coverage:
      bbox: [20, -9.99999999998001, 59.999999999984, 40]
      bbox_srs: EPSG:4326
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: SRTM
      transparent: true
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']


  airports_wms:
    coverage:
      bbox: [20, -9.99999999998001, 59.999999999984, 40]
      bbox_srs: EPSG:4326
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: Airports
      transparent: true
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']

grids:
  osm_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw 

  osm_grid2:
    #this srs and origin specify a grid that can be used elsewhere in the configuration. In this example it is used for the osm_tiles source. These settings are correct for openstreetmap.org tiles.
    #The google mercator srs is used (also called EPSG:900913), and the origin of the tiles is north-west). If you get this wrong, you might very well get an all-blue world.
    srs: EPSG:900913
    origin: nw


globals:
  cache:
    meta_size: [6, 6]
    meta_buffer: 20
    lock_dir: './cache_data/locks'
    # where to store lockfiles for tile creation
    tile_lock_dir: './cache_data/tile_locks'
  http:
    ssl_no_cert_checks: true
    # image/transformation options
  image:
      resampling_method: bilinear
      jpeg_quality: 95